#spring.application.name=ecom
#
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:ecomtestdb
#spring.jpa.show-sql=false
spring:
  application:
    name: ecom
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:ecomtestdb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create