#spring.application.name=ecom
#
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:ecomtestdb
#spring.jpa.show-sql=false
spring:
  application:
    name: ecom
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomdb
    username: ecom
    password: ecom
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:ecomtestdb
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
